apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./firefly3
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # This is the magic block that enables SOPS decryption for this cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age