# Replica Count
replicaCount: 1

# Image
image:
  repository: postgres
  tag: "15-alpine"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Service Account
serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

# Pod Labels / Annotations
podAnnotations:
  seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
podLabels:
  app.kubernetes.io/part-of: finance-db

# Pod Security Context
podSecurityContext:
  fsGroup: 999
  fsGroupChangePolicy: "Always"
  seccompProfile:
    type: RuntimeDefault

# Container Security Context
securityContext:
  runAsUser: 999
  runAsGroup: 999
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

# Service
service:
  type: ClusterIP
  port: 5432

# Persistence
persistence:
  enabled: true
  storageClassName: local-path
  accessModes: ["ReadWriteOnce"]
  size: 5Gi
  mountPath: /var/lib/postgresql/data

# Environment Variables
env:
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-finance-creds
        key: POSTGRES_PASSWORD

# Resources
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

# Health Probes
livenessProbe:
  tcpSocket:
    port: 5432
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  exec:
    command: ["pg_isready", "-U", "firefly"]
  initialDelaySeconds: 10
  periodSeconds: 5

# Autoscaling
autoscaling:
  enabled: false

# Scheduling
nodeSelector:
  db: "true"

tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity: {}
