{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "firefly3.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "firefly3.labels" . | nindent 4 }}
  annotations:
    # Pin PVC to SSD node (cluster1)
    volume.kubernetes.io/selected-node: "cluster1"
    # Helm bookkeeping
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
