apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-cloudflare-tunnel-remote
  namespace: cloudflared
spec:
  template:
    spec:
      containers:
        - name: cloudflared
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared
                  key: tunnelToken