apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:GVaPT2tSLRtxmPblUVNgMgL4zSmuPLLIHvIIU0hyGNBuJPdVYQKc8dfKBAedARMWjj5Tfbl536iK3jkB0bO3lBCVNRy8j0zfdR0NQqcVtkhp1jtB6DbO638+Y+dD/pVZ8xdds5cgdVFEZzZD0dBtMm5PNWcCO+4rKs2cT02b0W22ZQDE5LseFo6RNUswfCqVGR+Eo2C12pRWDN3UyfwSWT3q74ejolEyg8h+FZ/6/cRCG6ItF0R1Jw==,iv:h69r6JzA79rVLIJxc8t4m7Q8DMmnjPU0YcmDystgoj0=,tag:TnEtLoPjQyFWjKcPZO/dTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucnNLUDVMOHBpNDdUenRE
            TTZtZjVrZWNsWXA2aUhQdVBZa2x1TCttUEhRCmdYVjdPVGtlN0MwZmlaZnozbEVL
            ai90QXNCelF6c0ZIendrelZwbHhkZmcKLS0tIENiaS94Y3hjQlJVS3NhTTl2Q3ZO
            SlVDWmJNbEtTNk5rMnpDck9GTkFGM1UKQwc9U2/nylTWC50R9veQxtv1CRWdTI4G
            Yw/gXK8JEd/GYd5q7xKaZxLqXcqegkyCvGBZLFO9Lb46mKrdxidlcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T01:46:04Z"
    mac: ENC[AES256_GCM,data:ugjAMl+DLxTzuVIDEScwW1S068IzTSrZSJyfrvr4RzLrn9zbHiCjftzw8tpdFzJnNReI40hw3832NNMhNaAblGOgasVeJaAPT4gCWWFSpAQaES7fVIdut+kKLGrc89s5qxnAZXs3EwE728tIYUZRIf1rUWUEOV+aQB0pA3GYHP8=,iv:vsFWQ5vF0X4sM7Sco0u9geI3ADs7dOkSD9o3ZcHGPVI=,tag:HYvJj/LKWvb9dww27q49mw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
