apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-cloudflare-tunnel-remote
    namespace: cloudflared
annotations:
    kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    tunnelToken: ENC[AES256_GCM,data:/8M7zvxrdsSUaOtguel0W9v+Z/gxFAfJCtNqf21ytUJVPz4mhkB2UaIh0duSdaltw0qayDSqo4JHZpdI+y+QcQSPPCs1xaQUiFmHJsN/yAU2kbg2udQt04dVNkecpCHWJD75ZTNX8Eq9iEDNWexZzQhn2pOIvlHMNrCzAUQ8h4tojFwTuU4g1Q8i5ai4RWzPSuwuqjMcNk6EKLkDDZzVofP7wUl+UyapyF9m25P/Dgn+4AajapAhng==,iv:j/lFamOgzIaW60rIy/kASxRBj6N5W14goY6OyNJfBhM=,tag:06IS+oSSfT4oeKVMqh6OpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTmc0ZHZZWTBSdVE3T1FG
            SS9pT1lBWkpZTzNZQ1J1dUtYeEFINmJ0bXdrCkN0czFQQXo2RlNqTTdhZng3bkRT
            bkFKY21iTjlYWnZZb1lnMGUxTWRRMlUKLS0tIFBlcStPWHBYNFB3d3FmYkl0NHYv
            cGxMS3RGVFI1b1JhUi94bk1jdnY5OU0Kf8o6mVk+mVpoEyRZT5vIw3jUsed9P6+M
            ZdTxkSNs/Fy3dMTAF3xeHFhTOO3LsqTJWdzsTpsXLgdgOggPijRvOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T03:18:08Z"
    mac: ENC[AES256_GCM,data:Tpzaqvqs0gaj2soBA2BNfZgHqUvmtd/8rS2jCVZT95tOhAqLAXg8XrmAYt+Kpou26jKFXamYuOiBYEp/XWrgzldWk1DWDONuZt1cb+0dZGelMTg0GDDRGfOHqfAia/KzG5wRpSnr+/FDXsTuBDWkPSC0Kpg/KBqY+RK696Kgc/Q=,iv:V5hO7U/ZZooDklJ1lWYbmJ+c6D4e69edMqGRsGC2PcM=,tag:HpWX0Xe6aOybkj5viQ8evw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
