apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:p1IQSCLC336q6myOsVwN5ef/kO+hnNrL8PfaLO3Uo8+I1JIsls9uMPFhuhHht7cvvmsfUESUcAlDwr/3unxKrDNsy+loJgs1wokip/HumCYk1WMvwlI4ASOjVytqSngxm9lKpQRurBoqhGxhJ6KllKggA2vAcPuSvo4yG3q/moBXP0mkGagU/NsO1u6KkRZTZqH58VpczePM82cMcoJHSPpfoYedR8VJ+oPsPgLGuXISbNG4fYmzfso5o12VStFGYf18oGDXLk7um/ZgAyAQ/yp/CbVWNQeRi3kw+4Dke3maHGC163dTPN6KdT//mSfIM9rmUYO+zAHgP0vEt93Kh6ZeaOfEQ0CF5jd895zOlYTEU8UL3CX+mc0xAJoOyw==,iv:KLVoa8V3x7KkdV0EQ5wYqbPjb1Oqdsj3yy+knpHaypI=,tag:NheWDChVtAFFllbNaodd5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkelRFd2YxVjNnTExDWXhq
            RVkrakVsL0NNRTdKUnZqUHh4bEtjS255WXpzCjMxbjZnUHhXeDJPNDYwR0NNcTZX
            TDd0Ylk4U29wRlIvVXY4WXNPR2xYN0UKLS0tIHFOZS80ODV1OVkxL0Y5b3ZxV2J4
            NU1rMzFuZkR3ZE44ZTdDK1FDUmlrUDQKEXKSWYUh9K9cD5NVJKrjMUx3TbGoa+Ud
            tZiiLysYYxdYbLjLi/+t9VNoRaghbDCCPcwguGJ6gTkbK9MYYZ/6Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T02:14:29Z"
    mac: ENC[AES256_GCM,data:1R5lXHfN/zJIwyhQgaLtC8LCUvRO0gwU2kSr/mSV+DZW+mK9BXkdYIrSCrL2KpEyygc+1pIBpOuu+7S4yFihoScdI3DRJyEquzTkfalZ9MmzelCSMEeVhLm7+rgRWY03EFTMN9muM+uRrTYOc/R+JbhzpACR6Of4sb+8hY2DDSA=,iv:dFiNMdexA3+koMssOGydYbgo4LPjW/gXBX8GXpq1WYo=,tag:yrlkVZEXJx8qCiQO0ZYBnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
