apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  values:
    replica:
      allNodes: false
      count: 2

    nodeSelector:
      node-role.kubernetes.io/ingress: "true"

    tunnelSecrets:
      existingConfigJsonFileSecret:
        name: cloudflare-tunnel-token
        key: credentials.json

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi