apiVersion: v1
kind: Secret
metadata:
    name: firefly-db-credentials
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Mg1qeYX7+Q==,iv:BbIhhQxF9fyLFlpXhXGiQH5QpiG8ZVs+h7mmoBy185s=,tag:r7E8TL1iENPzblMUA/1y+g==,type:str]
    password: ENC[AES256_GCM,data:QxCBDRWF0XM99kW1iPH9iXm9Io4=,iv:hIrQqWZPCFnvRqMWqnAXfesQz3xzbgD9mKxgUcX5VzE=,tag:Lp1jFpSB54XPr7wboZtfdA==,type:str]
    database: ENC[AES256_GCM,data:RoKVe5orcQ==,iv:AeeWH7SjoNG1ihAkVU9NxGRGRXbeHYcCvaAoQegc+Z4=,tag:mbhHfAdwJR7Pl+E2AJQYcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYVpQMHIwQ1hBYXZLMXRa
            Q3VEV0N5cGRWYWorQ0VXM3ZXc0FMWXdOc0ZrCkpuQWpYL3RCa2EzcTdsdFlnSHQ5
            dXZWZ0JxY2F1VGpKN2xubTEwbFcvWjQKLS0tIC9RMkFvRHhUcjMzRE5VZHo5cVRP
            UkdybUxRd1YvSngxbHovOU05WXpjVE0KxrjT/WycfExTKf5OvqQEh0ElmliCwusY
            R7fNcIAdmSVkVYLZox6Zhw8u6OuBbzG7Ik0jE/GMW+sZli4h97GSvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T05:05:29Z"
    mac: ENC[AES256_GCM,data:TOfHl3SmrdYPmBwooXAc4hcNYWBuompCcGu06Mx2Vx6UpwoEo70U7OEP21razboFJncoo5IAk/u14QN8c/T0i3vky81aq++lA9UFe2Y1Xkefsm4qrE8P8WgFVnIMC2ksRgfGCywUuFDOsL6LJ5LrPIt243K7UivbM3ZCWj6tBqI=,iv:PuVQr76Kd0Vx6rm/FIMHOsbDRNSne/yZaWln7gWmKfI=,tag:p/0jIRR835+m4YV3hCJNQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
