apiVersion: v1
kind: Service
metadata:
  name: {{ include "wikijs.fullname" . }}
  labels:
    {{- include "wikijs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "wikijs.selectorLabels" . | nindent 4 }}
