apiVersion: v1
kind: Secret
metadata:
  name: wikidb-admin
  namespace: wiki
type: Opaque
stringData:
  DB_HOST: "wiki-postgres"
  DB_PORT: "5432"
  DB_USER: "wikijs"
  DB_PASS: "9MytpJ$5nEDD%$4$c3Xt"
  DB_NAME: "wikijs"
  DB_TYPE: "postgres"
