apiVersion: v1
kind: Pod
metadata:
  name: net-debug
  namespace: wiki
spec:
  containers:
    - name: net-debug
      image: alpine:latest
      command: ["sh", "-c", "sleep 3600"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
  restartPolicy: Never
