apiVersion: v1
kind: Service
metadata:
  name: wiki-postgres
  namespace: wiki
  labels:
    app: wiki-postgres
spec:
  type: ClusterIP
  selector:
    app: wiki-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wiki-postgres
  namespace: wiki
  labels:
    app: wiki-postgres
spec:
  serviceName: wiki-postgres
  replicas: 1
  selector:
    matchLabels:
      app: wiki-postgres
  template:
    metadata:
      labels:
        app: wiki-postgres
    spec:
      nodeSelector:
        db: "true"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432

          envFrom:
            - secretRef:
                name: wikidb-admin

          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wikidb-admin
                  key: db_pass
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: wikidb-admin
                  key: db_user
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: wikidb-admin
                  key: db_name
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "wikijs"]
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wiki-postgres-pvc
