apiVersion: v1
kind: Secret
metadata:
    name: firefly-firefly-iii-app-key
    namespace: firefly
type: Opaque
stringData:
    app-key: ENC[AES256_GCM,data:zJH8N0ykt7RrwWXLzVSZKSoy6caQHQSkt111Kpe1k8Y=,iv:TkJ4k7fbCbaulYkKpf5B2q304Ez282VTV2q86Biaw6c=,tag:IqxhO2n855U1PXBqqHFMcQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:z7f/imyCHZOVlF4m3bEbDwT9BTPQwmrzxZ6w3cYeGIg=,iv:TLPK6/dOB0iZwW+lHVCUS/cPl8R4hCF9jKNb9tmCE7g=,tag:ZoDPUPTzvEnT6T9sD1vM+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQlJVOTh2M01DWkRBZGdx
            MUpncEM5cFhWd0kzM1RHWEFaYmV4MHNxcHlrCjIvd3djeU5KTkY2QTFjek5EZmNn
            Qlo5cjF2Q043RUY0V0tqQzV1T0xpOEkKLS0tIFJNR3c3dUNhOEwybzl1RjRMKzZW
            NEQ5S0thLzl2cmN0cmdzbVhjN1NnR0kKlupT/hlL64v9mAjMreImMx9sNUXEhoRn
            9dMBBu4aA9cgPK0nbFn4+wnVJoQVIs8r6bo9oyBgbVjzGFzwdVCl6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T01:50:04Z"
    mac: ENC[AES256_GCM,data:Qde+mDaEv+LdBIOpUMAQXAlxuCcwy0AM1TuZZ/2muAmFpsNDuuAsR4OGXlaGfxX6p/b55pEGbmbGtzv+SYqJ/Tdyc8A02DsZWxJSXfpyjs1GHpdJikv1fduKyROSeJirmnjW9BZbuwtUOcVVlh+dE0Vtc2SE7ItCgVZjMHsnerc=,iv:pk/3o7/H/OXvLJpEKk4yBdAlFVnKdGXLA/++5HSTLTs=,tag:yOXdNZXW2awteLaHBmuDmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
