apiVersion: v1
kind: Secret
metadata:
    name: firefly-firefly-iii-app-key
    namespace: firefly
type: Opaque
stringData:
    app-key: ENC[AES256_GCM,data:/wKcR8fQILIpQGMUwuwZOALXASU1Ysv5OG/R+35icPQ=,iv:DwmkNWBbREXIIWw/kfvljW4GFcG7mKvPN9VNRkpcZuI=,tag:FE8EZXWpB86lJKhwVmv8LA==,type:str]
    APP_KEY: ENC[AES256_GCM,data:qVkMlaX2XV8tkkgFDm8tJ6QmfmyUnYsdR3KPJ5EZO8c=,iv:wN7DFkZWXjoJDmvnS9xrEJ6LCJI0rkDoV8T0W/SrC+Q=,tag:ENGzhPuB7ifXpBxtvjOrtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUEJrU1ZqYjVQOHVzaVR6
            V0R6V1M0TFFBVHB1d3Ztem5jMFViUFNJbXdFCkowbWdKaHdRQ2QvMHZZZDNrVURE
            SVVZcjNIU2NZLzZpZ2p6SkpYWkFwVFkKLS0tIGtTTUZGRldTZWt5dDk5QlFyWkJl
            Mlo0RVRVdE9FWmwrUXFqZFV3RThLNk0KeoIItOCn+Ta5blUFUZ0rQyjEbapxj8pE
            I5N2kU21CCK7vfnbOcwCC0t1a9qAycbYus4YkT/OhlWYHrRXXfzAhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T02:15:54Z"
    mac: ENC[AES256_GCM,data:FTvwJrVR5E90rhzCehtGA9P9gJ21uY1ZQdhFYAKTkbDGNBg4zLUAjCdIPVTkCgPaB01zxRDpKZH6aaRAcyX2XBXDYWgIaYx7AU4fTMV1NjBOwg5bXmNYAzCPOUX80nVhx1G18uNy7HDSG3sdR+LxjdyVhdxKvmuxnrLzPA1svvA=,iv:p9TchHronfiZYYbKjciG7VHCbT9J/b+fSVoVM+y8u+4=,tag:ocZw7gydvsvAwbJf0a3S1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
