apiVersion: v1
kind: Secret
metadata:
    name: firefly-secrets
    namespace: firefly
stringData:
    db-password: ENC[AES256_GCM,data:xVDk4S42Gc/tWkGAAj1hhnm2v4RoCD7IvSuTnCN5,iv:nxSG5NhDOVU2oVaAhMESLe+6C8sPspNQHwF/Es44GVc=,tag:MoMDASw0dmaJtaKthbr14Q==,type:str]
    app-key: ENC[AES256_GCM,data:XIQcXx/VYdfYAxntqqJY383wMwaBi8DuoKLT92DSD78=,iv:3uFGKFSDLcQVk2vXvHaeM+JF9roafBLY5KOymPlWutY=,tag:yTStbLQ3Wkig5eZ/hZR0tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXV2E2RTI5NFc5bG0rdXJz
            UlhTTklFUFlOdHlnU3NYMTRDVEMzbDZmMENvClFkOUVWYUF0SXdITTN5YllBbDZl
            NVVaaE05Z3V1aFJmSUdkUnpNanZDNEUKLS0tIGVBWTg4Z1lsNzIvSnpzK1hVdWVK
            Q3Fxc3JxMEpCeExYUXBXL3FNYVl2ZXcKmnuLIqd6pf12l1EH144cpHd9KbINmkbw
            fWO/e1U3K8e/qQTro1cP1su8kIURJPmzqalYJXLT4TmCq8700GH1kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T01:25:29Z"
    mac: ENC[AES256_GCM,data:F6Iwp0DHmC590iI9DsbBomWJbb6z80Lgo3rXwf9lghaHTOSiOLPjNNzJDZbEHpTbwWrvdU1Pde8kopRtrHUdilNMfQ2dRPLnJDIaSdjXvhPDvGSGCEjcAYrFpPHPI4Y8c6MNn1JXXlkV91YqZ5FvoNZ+a0W6sBx6K9EJXW7zFdw=,iv:KmwDnz03VfSo3IkuSkIv+MAWL1dZOOcG5X3hHhZtUts=,tag:5WaIgDvx/sTn5feNE2xblA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
