apiVersion: v1
kind: Secret
metadata:
    name: firefly-firefly-iii-app-key
    namespace: firefly
type: Opaque
stringData:
    app-key: ENC[AES256_GCM,data:SZG+sJPLb5xixU0ZKDRuk4Mv5NdwTEOa8DVuNH4Odlo=,iv:rDZCHUZTfCfPARgVsRB1LNwUAirxz1JIlaoT+wdifAc=,tag:SXOCXPPoHO8hCOV/X5nhYQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:IudnCIgNzYqnzUPq5Q0ugKkmbuLWfMRQUwKqO0VCjEM=,iv:uzuSrcdepBM/5WHCCduBoLEbO4fbHtesYtaRSOD2mes=,tag:NuDOfEfF4M6yLIkEtEjTtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dEJEMlQzK1lmMVhKM0tp
            OVRreUhDQlYxWlFiLzFleWUwV1AzQjVheEI0CjY0SkdlL0lQSzhsWHp5dCsvZ24z
            ajltUVhub0pLd2c5NHNnYmplMFZoemMKLS0tIGEvbmE4Y2wvTk9HTm5wWGtlUndZ
            V3d5YmNzQW1uMElDamZMWXoxVHlVTUEKqX0JeTGE0Aoe3Gki78vwIVZGeBt846E3
            iChmBeJqKZI9/swbX1NbNxtO07kGlycLSpYABu9TIgTTkYv0M2KFiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T01:45:42Z"
    mac: ENC[AES256_GCM,data:JgmQAOhbw+L0g92PPM4/9ArXrFbEvO0HaXNl82LCFkh8q95hzvx5U2/KgW7wo7G/c5QfIERe8jccI+DgJGOXjtcTPtu6ZsOLY5J0w8mlzoEhVitlZs6FVft2LQSjOS5f7xZroNB3iBK08N7NJ5ec8uUxmqa/cI3NHg22B48Nok0=,iv:BLthoG1Oh30KlXcGn5IC0DkVdGvYO9NhXz2MBG5q6aY=,tag:/bxXxpAk8p9NxxnJyUINFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-firefly-iii
    namespace: firefly
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:d8brKOK1KZc8PLWPz6fIy5Z2gstn5O6Mfs/9vK0t,iv:EYbMUqpGF15SfgkudXnGaw79Cj7sXk/A2B6eEl2UM1c=,tag:2GGD/LdCQlZIkX+4hpUSsg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Xt5HsxB81igUwT+5yHnkRR81OKYnW0Rtw1gV6M9j,iv:V5hR8FNHuyNtH/P33ln6ps6WXPICVEee9S1s+b9L+Zc=,tag:9Vc5+fEGPg6jfpxKsiEWOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dEJEMlQzK1lmMVhKM0tp
            OVRreUhDQlYxWlFiLzFleWUwV1AzQjVheEI0CjY0SkdlL0lQSzhsWHp5dCsvZ24z
            ajltUVhub0pLd2c5NHNnYmplMFZoemMKLS0tIGEvbmE4Y2wvTk9HTm5wWGtlUndZ
            V3d5YmNzQW1uMElDamZMWXoxVHlVTUEKqX0JeTGE0Aoe3Gki78vwIVZGeBt846E3
            iChmBeJqKZI9/swbX1NbNxtO07kGlycLSpYABu9TIgTTkYv0M2KFiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T01:45:42Z"
    mac: ENC[AES256_GCM,data:JgmQAOhbw+L0g92PPM4/9ArXrFbEvO0HaXNl82LCFkh8q95hzvx5U2/KgW7wo7G/c5QfIERe8jccI+DgJGOXjtcTPtu6ZsOLY5J0w8mlzoEhVitlZs6FVft2LQSjOS5f7xZroNB3iBK08N7NJ5ec8uUxmqa/cI3NHg22B48Nok0=,iv:BLthoG1Oh30KlXcGn5IC0DkVdGvYO9NhXz2MBG5q6aY=,tag:/bxXxpAk8p9NxxnJyUINFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dEJEMlQzK1lmMVhKM0tp
            OVRreUhDQlYxWlFiLzFleWUwV1AzQjVheEI0CjY0SkdlL0lQSzhsWHp5dCsvZ24z
            ajltUVhub0pLd2c5NHNnYmplMFZoemMKLS0tIGEvbmE4Y2wvTk9HTm5wWGtlUndZ
            V3d5YmNzQW1uMElDamZMWXoxVHlVTUEKqX0JeTGE0Aoe3Gki78vwIVZGeBt846E3
            iChmBeJqKZI9/swbX1NbNxtO07kGlycLSpYABu9TIgTTkYv0M2KFiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T01:45:42Z"
    mac: ENC[AES256_GCM,data:JgmQAOhbw+L0g92PPM4/9ArXrFbEvO0HaXNl82LCFkh8q95hzvx5U2/KgW7wo7G/c5QfIERe8jccI+DgJGOXjtcTPtu6ZsOLY5J0w8mlzoEhVitlZs6FVft2LQSjOS5f7xZroNB3iBK08N7NJ5ec8uUxmqa/cI3NHg22B48Nok0=,iv:BLthoG1Oh30KlXcGn5IC0DkVdGvYO9NhXz2MBG5q6aY=,tag:/bxXxpAk8p9NxxnJyUINFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
