apiVersion: v1
kind: Secret
metadata:
    name: firefly-firefly-iii
    namespace: firefly
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:u6IwLu76MQXW11mTafbAgGnmnMGQrIeQ4cDxvz++,iv:uhL9Klrose/K+pGOIUpP+ZU6f/2d2VVgTxR5pSj6vlY=,tag:lL0lqdob2p55ygoZisEqTg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:mohhcU4MB9WbaJoPP4scofvOlcl19sFMyzOsIa/p,iv:fbnoaqXEqdbmaZaaSa5d/y0Qyn8di5WGQVcB4ZgW1fk=,tag:D1guaoj+BHYmke2+PXg5Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsN2xTVERsNVltQ2lWNWFm
            Y1puYUNrQjdqcE90d1I2Q0R6azRTRk5RUFRrClM2akd1V3NjUjd0SVMzNE9Lc29O
            UmR5UFV5czg4ZDNIQjhhRUM0VWUyTEEKLS0tIG1QQk9VNEhJRGc4akpZa3dFbVhN
            N09HQmxKUmZGalBTbFZIWTJXVHRZeVUKRDks8DsTwpP+zO+zeVPQbfl6dZrA7Jhn
            YEqYR2Qy1lyLSXYLtnz1pYTJVQd3uKQ/pGt5IaGQW2WnZCMjrStbww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T01:50:10Z"
    mac: ENC[AES256_GCM,data:S8ZCj2stRlIgoKulwQ8S4rWu43MD+v0mRoYfA+A3ffhaPs2RMy5qiC9uD1gmHWov5FP3vxA+qUIMbC7JyYurB83D2DEs0oZKfyzaZCUaobnIY8dIBXAhNoFPpy6QxnFG1+Mhp7/jVX0cFLGWwFTuoHNRMVNOLK87NUjD1Xl/eno=,iv:ysGtPV0+Pol6wNsJLHEC+oMySuLZzeevy/nr+q5w4F0=,tag:515gmIM6ve5tQOh/WViSAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
