apiVersion: v1
kind: Secret
metadata:
    name: firefly-secrets
    namespace: firefly
stringData:
    db-password: ENC[AES256_GCM,data:pP2hj2wkQvhUQDAmfSCbqwE64OE=,iv:uS7tVkYUk8tUTe5flq5+NlT1AVXHDl9Fj6UU0+0U76g=,tag:qtW+lSoQ4oyxkh5fSejiug==,type:str]
    app-key: ENC[AES256_GCM,data:aByyWDFjMqHecMK4JPPT/5FkxWXT1jg3SDQcln9FEts1bsijR+TSLqQMWmVLgrPrJ3Ga,iv:nIH/ltBoMzQei4WdxBXAD1iSvWbFCaupQZmivu31Rvo=,tag:8pgcrSEL+OT4OyX4Ib1j0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hg2htg656ltg838gg7caspp68yhdxlvea985fva7k7p3u5sw5gkqxpttev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMk9mL29rbVhJUENvK3Ux
            am1vL2VFV2c3QUF5Uy9GQ2NqclY2UDBHMlM0CjJML2xhZzdZeE91cW9KMUd2N3JR
            V2JiVmZyR2R5ZlpWNkpvY0EzbGcvUDAKLS0tIEJ0U0g0WDk4em5yUHlMTW5sYzVH
            a0pZSzR6YUY0djQ3RUxDK05BdFFCWUkKjT5Md2qYPXRHvhqbFOWiccBrCThP/bNK
            bycD43mxomxlo9pHG7LLDSOZVmh+sI702Mf+MXKiFRzynEkvQssrnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T02:46:29Z"
    mac: ENC[AES256_GCM,data:XuvwjFutyaDIIt3z5M2l+jVHub5+gh3wXDDBlm/ukEP6kSQ4wdKfJ//vkGorPHseqkjYmXoh+K/6mJH6gbbYqWkuU+HXFLvUNV5dVFostsQLEwjDbeQc9nx4qGYAJAchD72mssFpT/IR3gQPqRdRVEPgmpGL0Gx6cETYceTEnv0=,iv:DVFJJRVFN/mRhQ10oERAvfAt8K77DY+M1PET8tLpsFU=,tag:OZqStFpVKQcpEkDHc/csdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
