apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firefly

# 1. Fetch the generic Base
resources:
  - ../../../apps/firefly3
  - firefly-secrets.yaml

# 2. Apply your cluster-specific values on top
patches:
  - path: release-patch.yaml
    target:
      kind: HelmRelease
      name: firefly