apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
  namespace: firefly
spec:
  values:
    # Subchart wrapper key for core app env
    firefly-iii:
      env:
        APP_URL: "https://firefly.henryhalldev.com"
        TZ: "America/New_York"

    backup:
      persistence:
        enabled: true
        storageClass: "local-path"
        size: 5Gi

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: firefly-firefly-db-postgre-db
            patch: |
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  node-role.kubernetes.io/heavy-compute: "true"

          - target:
              kind: Deployment
              name: firefly-firefly-iii
            patch: |
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  node-role.kubernetes.io/heavy-compute: "true"

          - target:
              kind: Deployment
              name: firefly-importer
            patch: |
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  node-role.kubernetes.io/light-compute: "true"

          - target:
              kind: CronJob
              name: firefly-firefly-db-backup
            patch: |
              - op: add
                path: /spec/jobTemplate/spec/template/spec/nodeSelector
                value:
                  node-role.kubernetes.io/light-compute: "true"