apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly
  namespace: firefly
spec:
  values:
    firefly:
      env:
        APP_URL: "https://firefly.henryhalldev.com"
        TZ: "America/New_York"
      ingress:
        enabled: true
        className: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
        hosts:
          - host: firefly.henryhalldev.com
            paths:
              - path: /
                pathType: ImplementationSpecific

    backup:
      persistence:
        enabled: true
        storageClass: "local-path"
        size: 5Gi

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: firefly-firefly-db-postgre-db
            patch: |
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  node-role.kubernetes.io/heavy-compute: "true"

          - target:
              kind: Deployment
              name: firefly-firefly-iii
            patch: |
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  node-role.kubernetes.io/heavy-compute: "true"

          - target:
              kind: Deployment
              name: firefly-importer
            patch: |
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  node-role.kubernetes.io/light-compute: "true"

          - target:
              kind: CronJob
              name: firefly-firefly-db-backup
            patch: |
              - op: add
                path: /spec/jobTemplate/spec/template/spec/nodeSelector
                value:
                  node-role.kubernetes.io/light-compute: "true"