apiVersion: v1
kind: Secret
metadata:
  name: firefly-secrets
  namespace: finance
type: Opaque
stringData:
  APP_KEY: "base64:UMvRCvifqH7ojIKyqJYDpWqe+82gHdE6qf89Rf3uEUo="       # Keep same key once generated
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres.finance.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "firefly"
  DB_USERNAME: "firefly"
  DB_PASSWORD: "m@qJRbm$2@n#NdN9sc6W"
  APP_URL: "https://firefly.henryhalldev.com"
  SECURE_COOKIES: "true"
  TRUSTED_PROXIES: "**"
