apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: firefly-cert
  namespace: finance
spec:
  secretName: firefly-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: firefly.henryhalldev.com
  dnsNames:
    - firefly.henryhalldev.com
